### ISSUE TITLE
Don't use the word polyfill and shim in the README, it's wrong.

### ISSUE THREAD

**Issue by MoOx** [MadLittleMods/postcss-css-variables#1]
This is a polyfill for custom props/css vars.

https://github.com/Polymer/polymer/blob/0.8-preview/PRIMER.md#custom-css-properties

You plugin isn't at all.

**Comment by MadLittleMods** [comment]
It provides future functionality by transforming variables into a static representation. I also prefaced it with "limited subset" because it does handle plenty of situations just fine.

Because CSS is a passive-type language, there is no way to get full functionality out of just CSS. While this plugin doesn't fit the exact concise definition, the keywords help people find this page who are looking for a solution.

> A shim is a library that brings a new API to an older environment, using only the means of that environment.
>
> [*Speaking JavaScript by Axel Rauschmayer*](http://stackoverflow.com/a/24391813/796832)

**Comment by MoOx** [comment]
> A shim is a library that brings a new API to an older environment, using only the means of that environment.

That my point, seeing the opened issue, you don't bring the new API at all. Just small pieces. And you forget the dynamic part (because we cannot) :p

**Comment by MadLittleMods** [comment]
I think the language now is pretty clear and functionality is fairly comparable to the real thing in many situations.
