### ISSUE TITLE
It does not work with @media?

### ISSUE THREAD

**Issue by nicothin** [MadLittleMods/postcss-css-variables#9]
before procesing:
<pre>:root {
  --screen-md: 768px;
  ...
}

@media (max-width: var(--screen-md)) {
  :root {
    ...
  }
}</pre>

after processing:

<pre>@media (max-width: var(--screen-md)) {
  ...
}</pre>
https://github.com/nicothin/test_area_PostCSS/tree/%40media_test — test

**Comment by ai** [comment]
BTW, it is a very Sassy way.

PostCSS way is to use CSS4 [postcss-custom-media](https://github.com/postcss/postcss-custom-media).

**Comment by ai** [comment]
@nicothin I think problem is that W3C spec is not allow to use CSS variables in at-rules. At least, I can’t find that example there.

**Comment by nicothin** [comment]
Well, this idiom with competent development
is a pity that it can not be used in the CSS-processing :(

**Comment by ai** [comment]
W3C speciallycreated Custom Media Queries for this cases ;-). Your engineer thinking is just limited by Sass way. You ask for one-to-one solutions and don't see benefits of other ways (like Custom Media is more explicit way with better support, because you can store all media breaks in one file and quickly understand on what media your style will be changed).

**Comment by MadLittleMods** [comment]
I can't find any example/support for `var` usage in media queries in the spec. Keep in mind that this plugin covers [CSS custom properties](http://dev.w3.org/csswg/css-variables/).

@ai's suggestion of [Custom media queries](http://dev.w3.org/csswg/mediaqueries-4/#custom-mq), [`postcss-custom-media`](https://github.com/postcss/postcss-custom-media) seems like a good option for your use case.
